recipe: default.v1
assistant_id: 20241023-205757-extended-seed
language: es

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  # Removemos el segundo CountVectorsFeaturizer para ahorrar memoria
  - name: DIETClassifier
    epochs: 50  # Reducido de 100
    hidden_layers_sizes:
      text: [128, 64]  # Capas más pequeñas
    embedding_dimension: 16  # Reducido
    number_of_transformer_layers: 2  # Reducido
    transformer_size: 128  # Reducido
    batch_size: 8  # Batch size más pequeño
    evaluate_every_number_of_epochs: 20
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1
  - name: RegexEntityExtractor
    patterns:
    - name: number
      pattern: '\\d+'

policies:
  - name: MemoizationPolicy
    max_history: 3  # Reducido de 5
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: true
  - name: UnexpecTEDIntentPolicy
    max_history: 3  # Reducido de 5
    epochs: 50  # Reducido de 100
    hidden_layers_sizes:
      text: [128, 64]  # Capas más pequeñas
  - name: TEDPolicy
    max_history: 3  # Reducido de 5
    epochs: 50  # Reducido de 100
    hidden_layers_sizes:
      text: [128, 64]  # Capas más pequeñas
    batch_size: 8  # Batch size más pequeño
    evaluate_every_number_of_epochs: 20
